"""HTML report generation for PaperTrail."""

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>PaperTrail — {date}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=DM+Serif+Display&family=Inter:wght@400;500;600&display=swap" rel="stylesheet">
<style>
  *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}

  :root {{
    --bg:        #F7F7F5;
    --surface:   #FFFFFF;
    --text:      #1A1A2E;
    --muted:     #6B7280;
    --accent:    #2D6A4F;
    --border:    #E5E7EB;
    --high:      #2D6A4F;
    --mid:       #D97706;
    --low:       #DC2626;
  }}

  body {{
    background: var(--bg);
    color: var(--text);
    font-family: 'Inter', sans-serif;
    font-size: 15px;
    line-height: 1.6;
    padding: 2rem 1rem 4rem;
  }}

  .page {{ max-width: 780px; margin: 0 auto; }}

  /* ── Header ── */
  header {{ margin-bottom: 2.5rem; padding-bottom: 1.5rem; border-bottom: 1px solid var(--border); }}
  .logo {{
    font-family: 'DM Serif Display', serif;
    font-size: 2rem;
    color: var(--accent);
    letter-spacing: -0.02em;
  }}
  .logo span {{ color: var(--text); }}
  .meta {{ margin-top: 0.4rem; color: var(--muted); font-size: 0.85rem; }}
  .keywords {{
    margin-top: 0.75rem;
    display: flex; flex-wrap: wrap; gap: 0.4rem;
  }}
  .kw {{
    background: var(--accent);
    color: #fff;
    font-size: 0.75rem;
    font-weight: 500;
    padding: 0.2rem 0.6rem;
    border-radius: 999px;
  }}

  /* ── Cards ── */
  .papers {{ display: flex; flex-direction: column; gap: 1rem; }}

  .card {{
    background: var(--surface);
    border: 1px solid var(--border);
    border-left: 4px solid var(--score-color, var(--border));
    border-radius: 0 8px 8px 0;
    padding: 1.25rem 1.5rem 1rem;
    transition: box-shadow 0.15s ease;
  }}
  .card:hover {{ box-shadow: 0 4px 16px rgba(0,0,0,0.07); }}

  .card-top {{
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 1rem;
    margin-bottom: 0.5rem;
  }}

  .title {{
    font-size: 1rem;
    font-weight: 600;
    line-height: 1.4;
    color: var(--text);
    text-decoration: none;
  }}
  .title:hover {{ color: var(--accent); }}

  /* Score pill + bar */
  .score-block {{ flex-shrink: 0; text-align: right; min-width: 48px; }}
  .score-pill {{
    font-size: 0.8rem;
    font-weight: 600;
    color: var(--score-color);
  }}
  .score-bar-track {{
    width: 48px; height: 3px;
    background: var(--border);
    border-radius: 2px;
    margin-top: 4px;
  }}
  .score-bar-fill {{
    height: 100%;
    border-radius: 2px;
    background: var(--score-color);
    width: var(--score-pct);
  }}

  .card-meta {{
    font-size: 0.78rem;
    color: var(--muted);
    margin-bottom: 0.6rem;
    display: flex; flex-wrap: wrap; gap: 0.3rem 0.75rem;
    align-items: center;
  }}
  .badge {{
    font-size: 0.7rem;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 0.04em;
    padding: 0.1rem 0.45rem;
    border-radius: 4px;
    background: #EEF2FF;
    color: #4338CA;
  }}
  .badge.preprint {{ background: #FEF3C7; color: #92400E; }}

  .abstract {{
    font-size: 0.875rem;
    color: #374151;
    line-height: 1.65;
  }}
  .abstract-short {{ display: block; }}
  .abstract-full  {{ display: none; }}
  .toggle-btn {{
    background: none; border: none; cursor: pointer;
    color: var(--accent); font-size: 0.8rem; font-weight: 500;
    padding: 0; margin-top: 0.3rem;
  }}
  .toggle-btn:hover {{ text-decoration: underline; }}

  .doi-link {{
    display: inline-block;
    margin-top: 0.6rem;
    font-size: 0.78rem;
    color: var(--muted);
    text-decoration: none;
    word-break: break-all;
  }}
  .doi-link:hover {{ color: var(--accent); }}

  /* ── Footer ── */
  footer {{
    margin-top: 3rem;
    padding-top: 1.5rem;
    border-top: 1px solid var(--border);
    text-align: center;
    font-size: 0.8rem;
    color: var(--muted);
  }}
</style>
</head>
<body>
<div class="page">

<header>
  <div class="logo">Paper<span>Trail</span></div>
  <div class="meta">
    {n_shown} of {n_total} relevant papers &nbsp;·&nbsp;
    Past {days} days &nbsp;·&nbsp;
    Generated {date}
  </div>
  <div class="keywords">
    {kw_pills}
  </div>
</header>

<div class="papers">
{cards}
</div>

<footer>
  Generated by PaperTrail &nbsp;·&nbsp; Sources: {sources}
</footer>

</div>
<script>
  document.querySelectorAll('.toggle-btn').forEach(btn => {{
    btn.addEventListener('click', () => {{
      const card = btn.closest('.card');
      const s = card.querySelector('.abstract-short');
      const f = card.querySelector('.abstract-full');
      const expanded = f.style.display === 'block';
      s.style.display = expanded ? 'block' : 'none';
      f.style.display = expanded ? 'none' : 'block';
      btn.textContent  = expanded ? 'Show more' : 'Show less';
    }});
  }});
</script>
</body>
</html>
"""

CARD_TEMPLATE = """  <div class="card" style="--score-color:{score_color};">
    <div class="card-top">
      <a class="title" href="{url}" target="_blank">{title}</a>
      <div class="score-block">
        <div class="score-pill">{score:.2f}</div>
        <div class="score-bar-track"><div class="score-bar-fill" style="--score-pct:{score_pct}%;"></div></div>
      </div>
    </div>
    <div class="card-meta">
      <span class="badge {badge_class}">{source}</span>
      {journal_span}
      <span>{date}</span>
      <span>{authors_short}</span>
    </div>
    <div class="abstract">
      <span class="abstract-short">{abstract_short}</span>
      <span class="abstract-full">{abstract_full}</span>
      {toggle}
    </div>
    <a class="doi-link" href="{url}" target="_blank">{url}</a>
  </div>"""


def _score_color(score: float) -> str:
    if score >= 0.5:  return "#2D6A4F"
    if score >= 0.35: return "#D97706"
    return "#DC2626"


def write_html(papers: list[dict], top_n: int, keywords: list[str],
               days: int, sources: list[str], path="papers.html"):
    from datetime import date
    from html import escape

    today = date.today().strftime("%B %d, %Y")
    subset = papers[:top_n]

    kw_pills = " ".join(f'<span class="kw">{escape(k)}</span>' for k in keywords)

    cards = []
    for p in subset:
        score = p["score"]
        color = _score_color(score)
        abstract = p.get("abstract", "")
        short = escape(abstract[:280] + ("…" if len(abstract) > 280 else ""))
        full  = escape(abstract)
        toggle = ('<button class="toggle-btn">Show more</button>'
                  if len(abstract) > 280 else "")

        journal = p.get("journal", "")
        if_val = p.get("if")
        if_str = f" · IF {if_val:.1f}" if if_val is not None else ""
        journal_span = (f'<span>{escape(journal)}{if_str}</span>' if journal and journal != "preprint" else "")

        authors = p.get("authors", "")
        authors_short = escape(authors[:60] + "…" if len(authors) > 60 else authors)

        is_preprint = p.get("journal", "") in ("preprint", "", None)
        badge_class = "preprint" if is_preprint else ""
        source_label = p.get("source", "")

        url = p.get("id", "")
        if url and not url.startswith("http"):
            url = f"https://doi.org/{url}"

        cards.append(CARD_TEMPLATE.format(
            score_color  = color,
            score        = score,
            score_pct    = min(score * 100, 100),
            title        = escape(p.get("title", "")),
            url          = url,
            badge_class  = badge_class,
            source       = escape(source_label),
            journal_span = journal_span,
            date         = escape(p.get("date", "")),
            authors_short= authors_short,
            abstract_short = short,
            abstract_full  = full,
            toggle       = toggle,
        ))

    html = HTML_TEMPLATE.format(
        date     = today,
        n_shown  = len(subset),
        n_total  = len(papers),
        days     = days,
        kw_pills = kw_pills,
        cards    = "\n".join(cards),
        sources  = escape(", ".join(sources)),
    )

    with open(path, "w", encoding="utf-8") as f:
        f.write(html)